apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"openshift.io/description":"Projeto API Admin","openshift.io/display-name":"API Admin","openshift.io/requester":"5W3X","openshift.io/sa.scc.mcs":"s0:c31,c10","openshift.io/sa.scc.supplemental-groups":"1000950000/10000","openshift.io/sa.scc.uid-range":"1000950000/10000"},"creationTimestamp":"2025-04-02T15:23:47Z","labels":{"kubernetes.io/metadata.name":"api-admin","pod-security.kubernetes.io/audit":"privileged","pod-security.kubernetes.io/audit-version":"v1.24","pod-security.kubernetes.io/warn":"privileged","pod-security.kubernetes.io/warn-version":"v1.24"},"name":"api-admin","resourceVersion":"1123573655","uid":"70051dfa-f168-4902-ab49-996f51e57899"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
    openshift.io/description: Projeto API Admin
    openshift.io/display-name: API Admin
    openshift.io/requester: 5W3X
    openshift.io/sa.scc.mcs: s0:c31,c10
    openshift.io/sa.scc.supplemental-groups: 1000950000/10000
    openshift.io/sa.scc.uid-range: 1000950000/10000

  labels:
    dynakube.internal.dynatrace.com/instance: zlon
    kubernetes.io/metadata.name: api-admin
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
  name: api-admin


spec:
  finalizers:
  - kubernetes
  phase: Active
