apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"openshift.io/description":"Ambiente de codificação ","openshift.io/display-name":"devspace","openshift.io/requester":"5W3X","openshift.io/sa.scc.mcs":"s0:c61,c15","openshift.io/sa.scc.supplemental-groups":"1003690000/10000","openshift.io/sa.scc.uid-range":"1003690000/10000"},"creationTimestamp":"2025-05-07T18:43:42Z","labels":{"kubernetes.io/metadata.name":"devspace","pod-security.kubernetes.io/audit":"baseline","pod-security.kubernetes.io/audit-version":"v1.24","pod-security.kubernetes.io/warn":"baseline","pod-security.kubernetes.io/warn-version":"v1.24"},"name":"devspace","resourceVersion":"1190497417","uid":"8e78d9df-07cc-4c0e-acc4-1acbfc27a0e0"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
    openshift.io/description: 'Ambiente de codificação '
    openshift.io/display-name: devspace
    openshift.io/requester: 5W3X
    openshift.io/sa.scc.mcs: s0:c61,c15
    openshift.io/sa.scc.supplemental-groups: 1003690000/10000
    openshift.io/sa.scc.uid-range: 1003690000/10000

  labels:
    dynakube.internal.dynatrace.com/instance: zlon
    kubernetes.io/metadata.name: devspace
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: v1.24
  name: devspace


spec:
  finalizers:
  - kubernetes
  phase: Active
