apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c32,c19
    openshift.io/sa.scc.supplemental-groups: 1001030000/10000
    openshift.io/sa.scc.uid-range: 1001030000/10000

  labels:
    kubernetes.io/metadata.name: dynatrace
    name: dynatrace
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
  name: dynatrace


spec:
  finalizers:
  - kubernetes
  phase: Active
