apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: Stack ECK Vibra
    openshift.io/requester: cluster-admin
    openshift.io/sa.scc.mcs: s0:c28,c17
    openshift.io/sa.scc.supplemental-groups: 1000790000/10000
    openshift.io/sa.scc.uid-range: 1000790000/10000

  labels:
    dynakube.internal.dynatrace.com/instance: zlon
    kubernetes.io/metadata.name: vbr-custom-eck
    olm.operatorgroup.uid/cbaf6ba7-b338-4b2c-99a0-3543e4320060: ""
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: vbr-custom-eck


spec:
  finalizers:
  - kubernetes
  phase: Active
